#!/bin/sh

VERSION=$(git describe)

mvn clean &&
sed -i s/version=.*/version=$VERSION/g src/main/java/org/eastway/echarts/client/EchartsConstants.properties &&
sed -i s/localhost/192.168.201.18/g src/main/resources/META-INF/spring/database.properties &&
mvn package

git checkout -- src/main/resources/META-INF/spring/database.properties
